### ISSUE TITLE
Provide cost metric for devices

### ISSUE THREAD

**Issue by avonwyss** [CometBackup/comet-prometheus-exporter#3]
Integer metric which would show the monthly $ cost of devices, with the same labels as `cometserver_device_is_online`.

Basically, this would be `2+boosters` for each device. It should reflect the fact that devices which have not been used yet are not billed, and the effective number of boosters used. This would allow to get a quick overview of the licensing status and how much credit is expected to use used on a monthly basis, optionally aggregated by user.

**Comment by mason-cometbackup** [comment]
This is a little bit tough, for two reasons -

1. Device costs are merged across all your Comet Servers (i.e. when replicating your Comet Server you are not charged for the duplicate device), so a single Comet Server doesn't have an accurate view of the billing by itself; and

2. The list of which Protected Items have "booster" charges attached is also time-dependent - that might change in the future if new Protected Item types are added, or if rarely-used ones were made free. You would need to update the Prometheus exporter when new information becomes available.

**Comment by avonwyss** [comment]
Maybe these metrics could be obtained from the cometbackup.com site along with available funds information, e.g. an aggregated form of https://cometbackup.com/reports/customer_usage with some aggregated available credit information? In this case these would not be added to the exporter here I guess, but rather as a separate endpoint on the cometbackup site.

**Comment by mason-cometbackup** [comment]
> In this case these would not be added to the exporter here I guess, but rather as a separate endpoint on the cometbackup site.

I agree, it's out-of-scope for this Prometheus exporter that is working on a per-Comet-Server basis.

The CometBackup.com website has been updated to add an API endpoint for this information - check out the new documentation at https://cometbackup.com/docs/api#reportactiveservices and raise a support ticket if you encounter any issues,

That doesn't solve the problem of actually getting this cost information into Prometheus. That might need to be a separate project.
