### ISSUE TITLE
Provide metrics for vaults

### ISSUE THREAD

**Issue by avonwyss** [CometBackup/comet-prometheus-exporter#4]
Two numbers seem especially important: the current size and the quota (by user and vault). The labels should probably list the ID and the friendly name of the vault as labels.
```
cometserver_vault_size_bytes{vault="x",user="y"}=123456789
cometserver_vault_quota_bytes{vault="x",user="y"}=200000000
```

This could be used for getting a storage usage overview and forecast, as well as user quota usage.

**Comment by mason-cometbackup** [comment]
I've added the `cometserver_storagevault_size_bytes` metric in 60966611484f4d219373d71ef0d514b5d11a68b2.

The quota metric is still outstanding.

**Comment by mason-cometbackup** [comment]
I've added the `cometserver_storagevault_quota_bytes` metric too.
